export const REGISTER = "auth/register"
export const LOGIN = "auth/login"
export const UPDATE = "/auth/updateUser"
export const JOBS = "/jobs"
export const GET_JOBS = "https://jsearch.p.rapidapi.com/search"